MyCompass/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCompass.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCompass.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly MyCompassContext _context;

        public MenuViewComponent(MyCompassContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var items = await _context.TripCategoriesModel.ToListAsync();
            return View(items);
        }
    }

}

MyCompass/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyCompass</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/ManagerOptions.css" />
</head>
<body>
    <header>
        @await Component.InvokeAsync("Menu")
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyCompass - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/Weather.js"></script>
    <script type='text/javascript' src='https://www.bing.com/api/maps/mapcontrol?callback=getMap&key=AqOux8LQ1nDtCOueAX9gCY85g9ZR2E8VX5ofXZVQs_fpe3fmOAHBG4_te0GtvYSh' defer></script>
    <script src="~/js/BingMaps.js"></script>
    <script src="~/js/ManagerOptions.js"></script>
    <script src="~/js/EventsNumber.js"></script>
    <script>
        window.fbAsyncInit = function () {
            FB.init({
                appId: '478986713131749',
                autoLogAppEvents: true,
                xfbml: true,
                version: 'v12.0'
            });
        };
    </script>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
    <script src="https://d3js.org/d3.v4.min.js" charset="utf-8"></script>
    <script src="~/js/d3/d3Pie.min.js"></script>
    <script src="~/js/d3/d3.min.js"></script>
    <script src="~/js/Statistics.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MyCompass/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication19</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3 justify-content-center">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>