MyCompass/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using MyCompass.Data;
using MyCompass.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Tweetinvi;

namespace MyCompass.Controllers
{
    
    [Authorize]
    public class HomeController : Controller
    {
        private readonly MyCompassContext _context;
        private readonly ILogger<HomeController> _logger;

        public string MyString { get; set; }
        public HomeController(ILogger<HomeController> logger, MyCompassContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var places = _context.PlacesModel.Include(c => c.TripEvents).Include(i => i.PlaceImage);
            return View(await places.ToListAsync());
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task<IActionResult> AboutUs()
        {
            string userDetalis = await twiter();
            return View("AboutUs",userDetalis);
        }

        public IActionResult Statistics()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public String TripCategoriesPieChart()
        {
            var categories = _context.TripCategoriesModel.Include(c => c.TripEvents).ToList();
            String result = JsonConvert.SerializeObject(categories, Formatting.Indented,
            new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return result;
        }

        public String PlacesPieChart()
        {
            var places = _context.PlacesModel.Include(c => c.TripEvents).ToList();
            String result = JsonConvert.SerializeObject(places, Formatting.Indented,
            new JsonSerializerSettings
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
            return result;
        }
 
        public async Task<string> twiter()
        {
            var userClient = new TwitterClient("5XMOijnEtAjiGRPgiKrZLAQRv", "CtCNBHB4ypLmkkeOSlbGTFt1slQHnT3hI46T9emHn0skA1Elui", "1459160998871457792-dDgIRs5r8ehEO8fbAehBhLADk2YHZS", "VpsigGR2sTaejvsmXn8arXZnlpw8dbVJzvrYIyj8eNVfE");
            var user = await userClient.Users.GetAuthenticatedUserAsync();
            string userDetalis = user + " number of twitter Followers " + user.FollowersCount;
            return userDetalis;
        }
    }
}

MyCompass/Controllers/TripEventsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCompass.Data;
using MyCompass.Models;
using MyCompass.Services;

namespace MyCompass.Controllers
{
    public class EventData
    {
        public int Count
        {
            get;
            set;
        }
        public string Place
        {
            get;
            set;
        }
    }

    [Authorize]
    public class TripEventsController : Controller
    {
        private readonly MyCompassContext _context;
        private readonly TripEventService _service;


        public TripEventsController(MyCompassContext context,TripEventService service )
        {
            _context = context;
            _service = service;
        }

      
        // GET: TripEvents
        public async Task<IActionResult> Index()
        {
            var webApplication16Context = _context.TripEventModel.Include(c => c.Place);
            return View(await webApplication16Context.ToListAsync());
        }

        public async Task<IActionResult> Search(string NameTrip,DateTime From, int Duration)
        {
            var trips = _service.Search(NameTrip, From, Duration);
            return View("Index", await trips.ToListAsync());
        }

        public List<EventData> CountNumberOfEventsByTrip()
        {
            List<EventData> placesObject = (from tripEvent in _context.TripEventModel
                                            join place in _context.PlacesModel on tripEvent.PlaceId equals place.Id
                                            group place by place.Name into g
                                            select new EventData
                                            {
                                                Place = g.Key,
                                                Count = g.Count()
                                            }).ToList();

            return placesObject;
        }

        // GET: TripEvents/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripEvent = await _context.TripEventModel
                .Include(a => a.Categories).Include(b => b.Place).FirstOrDefaultAsync(m => m.Id == id);

            if (tripEvent == null)
            {
                return NotFound();
            }

            ViewData["CategoryNames"] = new SelectList(_context.Set<TripCategories>(), "Id", "Name");
            ViewData["PlaceName"] = new SelectList(_context.Set<Place>(), "Id", "Name");
            return View(tripEvent);
        }

        // GET: TripEvents/Create
        public IActionResult Create()
        {
            ViewData["CategoryNames"] = new SelectList(_context.Set<TripCategories>(), "Id", "Name");
            ViewData["PlaceName"] = new SelectList(_context.Set<Place>(), "Id", "Name");
            return View();
        }

        // POST: TripEvents/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Categories,PlaceId,Date,Duration,Notes")] TripEvent tripEvent, int[] categories)
        {
            var errors = ModelState.Values.SelectMany(v => v.Errors);
            if (ModelState.IsValid)
            {
                var a = _context.TripCategoriesModel.Where(x => categories.Contains(x.Id));
                tripEvent.Categories = new List<TripCategories>();
                tripEvent.Categories.AddRange(a);

                _context.Add(tripEvent);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(tripEvent);
        }

        // GET: TripEvents/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripEvent = await _context.TripEventModel.FindAsync(id);
            if (tripEvent == null)
            {
                return NotFound();
            }

            ViewData["CategoryNames"] = new SelectList(_context.Set<TripCategories>(), "Id", "Name");
            ViewData["PlaceName"] = new SelectList(_context.Set<Place>(), "Id", "Name");
            return View(tripEvent);
        }

        // POST: TripEvents/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Categories,PlaceId,Date,Duration,Notes")] TripEvent tripEvent, int[] categories)
        {
            if (id != tripEvent.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var a = _context.TripCategoriesModel.Where(x => categories.Contains(x.Id));
                    var UpdateTripEvent = _context.TripEventModel.Include(t => t.Categories).FirstOrDefault(x => x.Id == id);

                    UpdateTripEvent.Categories = a.ToList();
                    UpdateTripEvent.Date = tripEvent.Date;
                    UpdateTripEvent.Duration = tripEvent.Duration;
                    UpdateTripEvent.Id = tripEvent.Id;
                    UpdateTripEvent.PlaceId = tripEvent.PlaceId;
                    UpdateTripEvent.Title = tripEvent.Title;
                    UpdateTripEvent.Place = tripEvent.Place;
                    UpdateTripEvent.Notes = tripEvent.Notes;


                    tripEvent.Categories = UpdateTripEvent.Categories;


                    _context.Update(UpdateTripEvent);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TripEventExists(tripEvent.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tripEvent);
        }

        // GET: TripEvents/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tripEvent = await _context.TripEventModel
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tripEvent == null)
            {
                return NotFound();
            }

            return View(tripEvent);
        }

        // POST: TripEvents/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tripEvent = await _context.TripEventModel.FindAsync(id);
            _context.TripEventModel.Remove(tripEvent);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TripEventExists(int id)
        {
            return _context.TripEventModel.Any(e => e.Id == id);
        }
    }
}

MyCompass/Views/Home/AboutUs.cshtml
@model string
@{
    ViewData["Title"] = "About Us";
}

<div class="text-center">
    <h1>About Us</h1>
    <h3>Hi !! We are an ambitious team who like to travel around our beautiful country.</h3>
    <div align="center">
        <canvas id="myCanvas" width="200" height="100">
            Your browser does not support the HTML5 canvas tag.
        </canvas>
    </div>
</div>

<script>
    var c = document.getElementById("myCanvas");
    var ctx = c.getContext("2d");
    ctx.font = "20px Arial";
    ctx.fillText("Introduction Video", 10, 90);
</script>

<div align="center">
    <video width="640" height="480" controls>
        <source src="~/Content/IntroductionVideo.mp4" type="video/mp4">
        Your browser does not support HTML5 video.
    </video>

    <br />

    <div class="fb-page col-md-3" style="margin-top: 2.7%" data-href="https://www.facebook.com/My-Compass-108529861645572" data-tabs="posts" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
        <blockquote cite="https://www.facebook.com/My-Compass-108529861645572" class="fb-xfbml-parse-ignore">
            <a href="https://www.facebook.com/My-Compass-108529861645572">My Compass</a>
        </blockquote>
    </div>
    <br />
    <div class="twiterFolowers row">
        <img src="~/Content/twitter.png" />
        <span class="col-6"> @Model</span>
        
    </div>
</div>

MyCompass/Views/Home/Index.cshtml
@model IEnumerable<MyCompass.Models.Place>

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <br />
    <h2>Welcome to My Compass Website</h2>

    @{
        <div class="row increaseRowWidth">
            @foreach (var item in Model)
            {
                <div class="col-2 mt-5 card" style="width: 14rem; margin-right: 7rem">
                    @if (item.PlaceImage != null)
                    {
                        string img = Convert.ToBase64String(item.PlaceImage.Image);
                        <img class="card-img-top" src="data:image/png;base64,@img" />
                    }
                    <div class="card-body">
                        <h5 class="card-title">@item.Name</h5>
                    </div>
                    <ul class="list-group list-group-flush">
                        @{
                            @foreach (var eventItem in item.TripEvents)
                            {
                                <li class="list-group-item">
                                    <a asp-action="Details" asp-route-id="@eventItem.Id" asp-controller="TripEvents">@eventItem.Title</a>
                                    <br />
                                    <div>@eventItem.Date</div>
                                </li>
                            }
                        }
                    </ul>
                </div>
            }
        </div>
    }
</div>

MyCompass/Views/Home/Statistics.cshtml
@{
    ViewData["Title"] = "Statistics";
}


@section scripts {

    <script type="text/javascript">
        
        var chartId = ["tripCategoriesPieChart", "placesPieChart"];
        function generateChart(url, id, title, subtitle) {
            var arr = [];
            $(document).ready(function () {
                $.ajax({
                    type: "GET",
                    url: url,
                    dataType: 'json',
                    async: false,
                    accepts: "application/json",
                    success: function (data) {
                        var randomColor;
                        data.forEach((value) => {
                            randomColor = Math.floor(Math.random() * 16777215).toString(16);
                            var piePeaceObject = {
                                label: value.Name,
                                value: value.TripEvents.length,
                                color: "#" + randomColor
                            }
                            console.log('piePeaceObject = ' + piePeaceObject);
                            arr.push(piePeaceObject);
                        });
                    }
                });

                getPieChart(arr, id, title, subtitle);
            });
        }

        generateChart('https://localhost:44323/Home/TripCategoriesPieChart', chartId[0],
            "Trip Categories Popularity", "A full pie chart to show the amount of trip categories around our website");

        generateChart('https://localhost:44323/Home/PlacesPieChart', chartId[1],
            "Places Popularity", "A full pie chart to show the amount of places around our website");
    </script>

}

<div class="text-center" id="tripCategoriesPieChart">

</div>
<div class="text-center" id="placesPieChart">

</div>